set nocompatible              " be iMproved

" Vundle
filetype off                  " required!
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'groenewege/vim-less'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'tomasr/molokai'
Plugin 'elzr/vim-json'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'octol/vim-cpp-enhanced-highlight'
call vundle#end()
filetype plugin indent on     " required!

let mapleader=","

" Keymap
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=-1

" Appearance
syntax enable
colorscheme molokai

" Line numbers
set number 

" indentation all
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" swap files
set noswapfile 

" file types 
autocmd FileType make setlocal noexpandtab
autocmd FileType html setlocal shiftwidth=2 tabstop=2

" search
set incsearch
set ignorecase

" search down into subfolders 
" provides tab-completion for all file-related tasks
set path+=**
" display all matching file when we tab complete
set wildmenu

" spellcheck (make sure Russian dictionary is set up)
nnoremap <F5> :setlocal spell! spelllang=en_us,ru_ru<CR>

" ctrl+s as save
inoremap <C-s> <Esc>:w<CR>
nnoremap <C-s> :w<CR>

" remove current buffer without closing window
nnoremap <C-c> :bp\|bd #<CR>

" buffers
nnoremap <C-h> :bprevious<CR>
nnoremap <C-l> :bnext<CR>
nnoremap <C-n> :buffers<CR>:buffer<Space>

" Backspace fix
set backspace=indent,eol,start

" folding
set foldmethod=manual
set foldlevelstart=1
let xml_syntax_folding=1

" marks
nnoremap <leader>m :marks<CR>

" nerd tree
nnoremap <leader>k :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen=1

" Airline
let g:airline#extensions#tabline#enabled = 1 " Enable the list of buffers
let g:airline#extensions#tabline#fnamemod = ':t' " Show just the filename
let g:airline_powerline_fonts = 1
let g:airline_detect_modified = 0
set laststatus=2
